
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crowdax_api_development

  host: localhost
  username: crowdax
  password: ihatepass

test:
  <<: *default
  database: crowdax_api_test
  host: localhost
  username: crowdax
  password: ihatepass

production:
  <<: *default
  database: crowdax_api
  username: deploy
 #password: <%= ENV['CROWDAX_API_DATABASE_PASSWORD'] %>
  password: Rails.application.credentials.dig(:production, :db_password)

