
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crowdax_api_development

  host: localhost
  username: crowdax
  password: ihatepass

test:
  <<: *default
  database: crowdax_api_test
  host: localhost
  username: crowdax
  password: ihatepass

production:
  <<: *default
  database: crowdax_api_production
  username: crowdax_api
  password: <%= ENV['CROWDAX_API_DATABASE_PASSWORD'] %>
